config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  resources :users, only: %i[index new create]
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = UsersList.call.get
  end

  def new; end

  def create
    UserWorker.perform_async(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email]
    )
    flash[:notice] = 'In the process of creating the user'
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Job Seeker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <%= render 'layouts/flash_messages' %>
        <%= yield %>
      </div>
    </div>
<script>
$(document).on('turbolinks:load', function(){
    $(".alert").delay(5000).slideUp(500, function(){
          $(".alert").alert('close');
      });
    });
</script>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_tag('/users', method: :post ) do %>
  <div class="form-group">
    <%= label_tag 'email', 'Email' %>
    <%= email_field_tag :email, '', class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= label_tag 'first_name', 'First Name' %>
    <%= text_field_tag :first_name, '', class: 'form-control', required: true  %>
  </div>
  <div class="form-group">
    <%= label_tag 'last_name', 'Last Name' %>
    <%= text_field_tag :last_name, '', class: 'form-control', required: true  %>
  </div>
  <div class="form-group">
    <%= submit_tag 'Create User', class: 'form-control btn btn-primary' %>
  </div>
<% end %>

app/views/users/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Email</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <th scope="row"><%= user['id'] %></th>
      <td><%= user['first_name'] %></td>
      <td><%= user['last_name'] %></td>
      <td><%= user['email'] %></td>
    </tr>
    <% end %>
  </tbody>
</table>
  <%= link_to 'Add New User', new_user_path, class: 'btn btn-primary'%>

app/views/users/new.html.erb
<h1>Create User</h1>
<div class="container">
  <%= render 'form' %>
</div>